#!/usr/bin/env bash
# Orbit SMTP Relay installer for Ubuntu and Debian.
#
# Installs or updates one relay node on the host it runs on:
#
#   curl -fsSL https://raw.githubusercontent.com/Oribt-AI/Orbit-SMTP-Relay/main/install.sh \
#       | sudo bash -s -- --server https://mail.example.com --key orbk_...
#
# The same command is printed, with the server filled in, by Orbit Mail under
# Settings, Encryption, and by Mission Control's Mail page for the fleet.
# Re-running it on the same host updates the node in place: its settings and
# the encryption key are remembered.
#
# What it does: installs Postfix and Python from the distribution, clones this
# repository to /opt/orbit-relay, generates the node's encryption key once,
# writes /etc/orbit-mail/relay.env with the server URL and API key, configures
# the host's Postfix to hand accepted mail to the agent, and runs the agent as
# the orbit-relay systemd service. Mail is sealed on this host with that key
# before it reaches the server; the relay has no readable mode.
#
# The relay runs directly on the host. Whether that host is a VM, a container
# or bare metal is the operator's choice; the installer needs only apt and
# systemd. A node an earlier release ran in Docker is moved out of its
# container, queue included.
#
# The script carries no secrets. The keys are written straight to
# /etc/orbit-mail, readable only by root and the relay's orbitmail user.
#
# Supported: Ubuntu 24.04 and newer; Debian 12 (bookworm), 13 (trixie) and
# newer. The agent needs Python 3.11, which Ubuntu 22.04 does not ship.

set -euo pipefail

SERVER_URL="${ORBIT_MAIL_SERVER_URL:-}"
API_KEY=""
NODE_NAME=""
RELAY_HOSTNAME=""
STATUS_PORT=""
TLS_CERT=""
TLS_KEY=""
REPO_URL="${ORBIT_RELAY_REPO_URL:-https://github.com/Oribt-AI/Orbit-SMTP-Relay.git}"
REPO_REF="main"
INSTALL_DIR=/opt/orbit-relay
ENV_DIR=/etc/orbit-mail
ENV_FILE="$ENV_DIR/relay.env"
KEY_FILE="$ENV_DIR/relay.key"
DATA_DIR=/var/lib/orbit-mail
SPOOL_DIR=/var/spool/orbit-mail
POSTFIX_DIR=/etc/postfix/orbit
SERVICE=orbit-relay
SERVICE_USER=orbitmail
MAIN_CF_MARKER="# Generated by the Orbit SMTP Relay installer."
# relay.env lines the installer writes; any other line there is the
# operator's and survives a re-run.
MANAGED_SETTINGS="ORBIT_MAIL_SERVER_URL|ORBIT_RELAY_API_KEY|ORBIT_RELAY_NAME|ORBIT_RELAY_HOSTNAME|ORBIT_RELAY_ENCRYPTION_KEY_FILE|ORBIT_STATUS_PORT|ORBIT_POSTFIX_DB_TYPE|ORBIT_TLS_CERT|ORBIT_TLS_KEY"

usage() {
    cat <<'USAGE'
Install or update an Orbit SMTP Relay node.

  --server <url>       Orbit Mail server URL (required on first install)
  --key <api-key>      Relay API key from Orbit Mail (Settings, Encryption) or Mission Control's
                       fleet key (required on first install)
  --name <name>        Node name shown under Relays (default: short hostname)
  --hostname <fqdn>    Hostname Postfix announces in EHLO (default: this host's FQDN)
  --tls-cert <path>    Certificate Postfix presents for STARTTLS (default: a self-signed one)
  --tls-key <path>     Its private key
  --repo <git-url>     Relay source repository
  --ref <branch|tag>   Git ref to install (default: main)
  --status-port <n>    Local port for the relay's status endpoint, 0 for none (default: 8080)
  -h, --help           Show this help

Every option is remembered in /etc/orbit-mail/relay.env, so a re-run needs
none of them. Mail is always sealed on this host before it reaches the server.
The key is generated once in /etc/orbit-mail/relay.key; copy that file to
another host first to have several nodes share one key.
USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --server) SERVER_URL="$2"; shift 2 ;;
        --key) API_KEY="$2"; shift 2 ;;
        --name) NODE_NAME="$2"; shift 2 ;;
        --hostname) RELAY_HOSTNAME="$2"; shift 2 ;;
        --tls-cert) TLS_CERT="$2"; shift 2 ;;
        --tls-key) TLS_KEY="$2"; shift 2 ;;
        --encrypt) shift ;;  # accepted for commands printed by older servers; it is the only mode
        --no-encrypt) echo "The relay always seals mail; --no-encrypt is not supported." >&2; exit 2 ;;
        --repo) REPO_URL="$2"; shift 2 ;;
        --ref) REPO_REF="$2"; shift 2 ;;
        --status-port) STATUS_PORT="$2"; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown option: $1" >&2; usage; exit 2 ;;
    esac
done

log()  { printf '\033[0;36m[orbit-relay]\033[0m %s\n' "$*"; }
warn() { printf '\033[0;33m[orbit-relay]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[0;31m[orbit-relay]\033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run this script as root (prefix it with sudo)."
# Commands below run as orbitmail, which may not be able to enter the
# directory the script was started from.
cd /

# --- Operating system ---------------------------------------------------------

check_os() {
    [[ -r /etc/os-release ]] || die "Cannot read /etc/os-release; only Ubuntu and Debian are supported."
    # shellcheck disable=SC1091
    . /etc/os-release
    OS_ID="${ID:-}"
    case "$OS_ID" in
        ubuntu)
            if [[ -n "${VERSION_ID:-}" ]] && [[ "${VERSION_ID%%.*}" -lt 24 ]]; then
                die "Ubuntu ${VERSION_ID} is too old; use 24.04 or newer (the relay needs Python 3.11)."
            fi
            ;;
        debian)
            if [[ -n "${VERSION_ID:-}" ]] && [[ "${VERSION_ID%%.*}" -lt 12 ]]; then
                die "Debian ${VERSION_ID} is too old; use 12 (bookworm) or newer."
            fi
            ;;
        *)
            die "This installer supports Ubuntu and Debian; detected '${OS_ID:-unknown}'."
            ;;
    esac
    command -v systemctl >/dev/null 2>&1 || die "systemd is required to run the relay."
    log "Detected ${PRETTY_NAME:-$OS_ID}"
}

# --- Settings -----------------------------------------------------------------

read_env_value() {
    [[ -f "$ENV_FILE" ]] || return 0
    grep -E "^$1=" "$ENV_FILE" | head -n1 | cut -d= -f2- || true
}

resolve_settings() {
    [[ -n "$SERVER_URL" ]] || SERVER_URL="$(read_env_value ORBIT_MAIL_SERVER_URL)"
    [[ -n "$SERVER_URL" ]] || die "--server is required on first install (the Orbit Mail server URL)."
    [[ "$SERVER_URL" =~ ^https?:// ]] || die "--server must be an http(s) URL."
    SERVER_URL="${SERVER_URL%/}"

    [[ -n "$API_KEY" ]] || API_KEY="$(read_env_value ORBIT_RELAY_API_KEY)"
    [[ -n "$API_KEY" ]] || die "--key is required on first install. Issue one in Orbit Mail under Settings, Encryption (or the fleet key in Mission Control)."
    if [[ "$SERVER_URL" =~ ^http:// ]]; then
        warn "The server URL is plain http. The API key will travel unencrypted; use https in production."
    fi

    [[ -n "$NODE_NAME" ]] || NODE_NAME="$(read_env_value ORBIT_RELAY_NAME)"
    [[ -n "$NODE_NAME" ]] || NODE_NAME="$(hostname -s 2>/dev/null || echo relay-1)"
    [[ -n "$RELAY_HOSTNAME" ]] || RELAY_HOSTNAME="$(read_env_value ORBIT_RELAY_HOSTNAME)"
    [[ -n "$RELAY_HOSTNAME" ]] || RELAY_HOSTNAME="$(hostname -f 2>/dev/null || hostname)"

    [[ -n "$STATUS_PORT" ]] || STATUS_PORT="$(read_env_value ORBIT_STATUS_PORT)"
    STATUS_PORT="${STATUS_PORT:-8080}"
    [[ "$STATUS_PORT" =~ ^[0-9]+$ ]] || die "--status-port must be a number."

    [[ -n "$TLS_CERT" ]] || TLS_CERT="$(read_env_value ORBIT_TLS_CERT)"
    [[ -n "$TLS_KEY" ]] || TLS_KEY="$(read_env_value ORBIT_TLS_KEY)"
    if [[ -n "$TLS_CERT" || -n "$TLS_KEY" ]]; then
        [[ -n "$TLS_CERT" && -n "$TLS_KEY" ]] || die "--tls-cert and --tls-key go together."
        [[ -r "$TLS_CERT" && -r "$TLS_KEY" ]] \
            || die "Cannot read the TLS certificate ${TLS_CERT} or key ${TLS_KEY}; pass --tls-cert and --tls-key with this host's paths."
    fi
}

# --- Packages -----------------------------------------------------------------

export DEBIAN_FRONTEND=noninteractive

install_packages() {
    log "Installing Postfix and Python from the distribution"
    # "No configuration": the installer writes main.cf itself, so debconf is
    # not asked for one that would only be overwritten.
    debconf-set-selections <<EOF
postfix postfix/main_mailer_type select No configuration
postfix postfix/mailname string ${RELAY_HOSTNAME}
EOF
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl git postfix postfix-lmdb python3 python3-cryptography python3-dkim python3-spf publicsuffix ssl-cert >/dev/null
    /usr/bin/python3 -c 'import sys; sys.exit(sys.version_info < (3, 11))' \
        || die "The relay needs Python 3.11 or newer; this host has $(/usr/bin/python3 -V 2>&1)."
}

# --- Source -------------------------------------------------------------------

fetch_source() {
    if [[ -d "$INSTALL_DIR/.git" ]]; then
        log "Updating relay source in $INSTALL_DIR"
        git -C "$INSTALL_DIR" fetch -q origin
        git -C "$INSTALL_DIR" checkout -q "$REPO_REF"
        git -C "$INSTALL_DIR" pull -q --ff-only origin "$REPO_REF" || true
    else
        log "Cloning relay source from $REPO_URL"
        git clone -q --branch "$REPO_REF" "$REPO_URL" "$INSTALL_DIR"
    fi
}

# --- Moving off Docker --------------------------------------------------------

# Releases before 3.1 ran the node in a container. Its queue may hold the only
# copy of mail the server has not accepted yet, so it is copied out before the
# container is removed. Docker, the image and the volumes are left for the
# operator to remove once the node works.

MIGRATED_VOLUMES=()

copy_volume() {
    local name mountpoint
    # Compose prefixes the project name; a container started by hand does not.
    for name in "orbit-relay_$1" "$1"; do
        mountpoint="$(docker volume inspect -f '{{ .Mountpoint }}' "$name" 2>/dev/null)" || continue
        [[ -d "$mountpoint" ]] || continue
        install -d "$2"
        cp -a "$mountpoint/." "$2/"
        MIGRATED_VOLUMES+=("$name")
        return
    done
}

migrate_from_docker() {
    local compose="$INSTALL_DIR/docker-compose.yml"
    if command -v docker >/dev/null 2>&1 && docker container inspect "$SERVICE" >/dev/null 2>&1; then
        log "Moving this node out of its Docker container"
        if [[ -f "$compose" ]]; then
            docker compose -f "$compose" down || docker rm -f "$SERVICE" >/dev/null
        else
            docker rm -f "$SERVICE" >/dev/null
        fi
        copy_volume orbit-relay-queue "$DATA_DIR"
        copy_volume orbit-relay-spool "$SPOOL_DIR"
        copy_volume orbit-relay-dkim "$ENV_DIR/dkim"
        # The container's own copy of the key, and supervisord's pid file.
        rm -rf "$DATA_DIR/state/relay.key" "$DATA_DIR/state/run"
        if (( ${#MIGRATED_VOLUMES[@]} )); then
            log "Copied the queue and state out of: ${MIGRATED_VOLUMES[*]}"
        fi
    fi
    # Also left behind by an install whose image never built.
    rm -f "$compose"
}

# --- Host ---------------------------------------------------------------------

prepare_host() {
    if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
        log "Creating the ${SERVICE_USER} system user"
        useradd --system --home-dir "$DATA_DIR" --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER"
    fi
    install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0750 \
        "$DATA_DIR" "$DATA_DIR/queue" "$DATA_DIR/state" "$SPOOL_DIR" "$SPOOL_DIR/incoming"
    install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0755 "$POSTFIX_DIR"
    install -d -o root -g "$SERVICE_USER" -m 0750 "$ENV_DIR" "$ENV_DIR/dkim"
    # Files copied out of a container belonged to the container's own user.
    chown -R "$SERVICE_USER:$SERVICE_USER" "$DATA_DIR" "$SPOOL_DIR" "$POSTFIX_DIR"
}

ensure_encryption_key() {
    if [[ -s "$KEY_FILE" ]]; then
        log "Using the existing encryption key in $KEY_FILE"
    else
        log "Generating an encryption key in $KEY_FILE"
        (
            umask 077
            printf 'orbp_%s\n' "$(head -c 32 /dev/urandom | base64 | tr '+/' '-_' | tr -d '=\n')" > "$KEY_FILE"
        )
    fi
    # The agent and Postfix's receive hook both run as orbitmail and need it.
    chown "root:$SERVICE_USER" "$KEY_FILE"
    chmod 0640 "$KEY_FILE"
}

detect_db_type() {
    # The table type main.cf names and the agent rebuilds; the distribution's
    # Postfix default is the one it is sure to support. Postfix's tools need
    # a main.cf, which "No configuration" does not create; an empty one means
    # every default.
    [[ -f /etc/postfix/main.cf ]] || install -m 0644 /dev/null /etc/postfix/main.cf
    DB_TYPE="$(postconf -h default_database_type 2>/dev/null || true)"
    DB_TYPE="${DB_TYPE:-hash}"
    grep -qx "$DB_TYPE" <<<"$(postconf -m)" || die "This host's Postfix does not support its own default table type '${DB_TYPE}'."
}

write_env() {
    log "Writing $ENV_FILE"
    local kept=""
    if [[ -f "$ENV_FILE" ]]; then
        kept="$(grep -E '^[A-Z_][A-Z0-9_]*=' "$ENV_FILE" | grep -vE "^(${MANAGED_SETTINGS})=" || true)"
    fi
    (
        umask 077
        cat > "$ENV_FILE.new" <<EOF
# Orbit SMTP Relay configuration for ${NODE_NAME}.
# Written by install.sh, which keeps any other setting you add at the end.
# Readable by root and orbitmail only: this file holds the relay API key.
# The settings are listed in the README under Configuration.

ORBIT_MAIL_SERVER_URL=${SERVER_URL}
ORBIT_RELAY_API_KEY=${API_KEY}
ORBIT_RELAY_NAME=${NODE_NAME}
ORBIT_RELAY_HOSTNAME=${RELAY_HOSTNAME}
ORBIT_STATUS_PORT=${STATUS_PORT}
ORBIT_POSTFIX_DB_TYPE=${DB_TYPE}

# This node's own key. Mail people write in Orbit Mail is sealed to it in
# their browser and opened here to be sent; inbound mail is sealed to each
# reader's key, fetched from the server.
ORBIT_RELAY_ENCRYPTION_KEY_FILE=${KEY_FILE}
EOF
        if [[ -n "$TLS_CERT" ]]; then
            printf '\nORBIT_TLS_CERT=%s\nORBIT_TLS_KEY=%s\n' "$TLS_CERT" "$TLS_KEY" >> "$ENV_FILE.new"
        fi
        if [[ -n "$kept" ]]; then
            printf '\n# Kept from the previous file.\n%s\n' "$kept" >> "$ENV_FILE.new"
        fi
    )
    chown "root:$SERVICE_USER" "$ENV_FILE.new"
    chmod 0640 "$ENV_FILE.new"
    mv "$ENV_FILE.new" "$ENV_FILE"
}

install_files() {
    install -m 0755 "$INSTALL_DIR/deploy/orbit-relay" /usr/local/bin/orbit-relay
    install -m 0755 "$INSTALL_DIR/deploy/orbit-relay-receive" /usr/local/bin/orbit-relay-receive
    install -m 0644 "$INSTALL_DIR/deploy/orbit-relay.service" "/etc/systemd/system/${SERVICE}.service"
    systemctl daemon-reload
}

# --- Postfix ------------------------------------------------------------------

configure_postfix() {
    log "Configuring Postfix as ${RELAY_HOSTNAME}"
    printf '%s\n' "$RELAY_HOSTNAME" > /etc/mailname
    chmod 0644 /etc/mailname

    if [[ -s /etc/postfix/main.cf ]] && ! grep -qxF "$MAIN_CF_MARKER" /etc/postfix/main.cf; then
        cp -p /etc/postfix/main.cf /etc/postfix/main.cf.before-orbit-relay
        warn "Replacing this host's Postfix configuration; the old one is /etc/postfix/main.cf.before-orbit-relay"
    fi
    [[ -f /etc/postfix/master.cf ]] || install -m 0644 /usr/share/postfix/master.cf.dist /etc/postfix/master.cf

    if [[ -z "$TLS_CERT" && ! -f /etc/ssl/certs/ssl-cert-snakeoil.pem ]]; then
        make-ssl-cert generate-default-snakeoil
    fi

    cat > /etc/postfix/main.cf <<EOF
${MAIN_CF_MARKER}
# Re-running install.sh rewrites this file; change its options, or
# /etc/orbit-mail/relay.env, instead.
compatibility_level = 3.6
myhostname = ${RELAY_HOSTNAME}
myorigin = \$myhostname
smtpd_banner = \$myhostname ESMTP Orbit Mail
inet_interfaces = all
inet_protocols = all
mydestination =
mynetworks = 127.0.0.0/8 [::1]/128
local_recipient_maps =
local_transport = error:local delivery is disabled

# --- Inbound: accept only the domains and addresses Orbit Mail told us about.
relay_domains = ${DB_TYPE}:${POSTFIX_DIR}/relay_domains
relay_recipient_maps = ${DB_TYPE}:${POSTFIX_DIR}/relay_recipients
smtpd_recipient_restrictions =
    permit_mynetworks,
    reject_unauth_destination,
    reject_unknown_recipient_domain,
    reject_unlisted_recipient,
    permit
smtpd_helo_required = yes
smtpd_sender_restrictions = reject_unknown_sender_domain
disable_vrfy_command = yes

# Everything accepted for a relay domain is handed to the agent, which seals
# it, queues it on disk and posts it to the Orbit Mail server.
relay_transport = orbit:
orbit_destination_recipient_limit = 1

# --- Outbound: mail submitted by the agent through sendmail goes straight out.
relayhost =
smtp_tls_security_level = may
smtp_tls_loglevel = 1
smtp_tls_CApath = /etc/ssl/certs

# --- Inbound TLS: opportunistic.
smtpd_tls_security_level = may
smtpd_tls_cert_file = ${TLS_CERT:-/etc/ssl/certs/ssl-cert-snakeoil.pem}
smtpd_tls_key_file = ${TLS_KEY:-/etc/ssl/private/ssl-cert-snakeoil.key}
smtpd_tls_loglevel = 1

# The agent refuses anything larger, so Postfix need not accept it.
message_size_limit = 52428800
maximal_queue_lifetime = 3d
bounce_queue_lifetime = 1d
EOF
    chmod 0644 /etc/postfix/main.cf

    # Empty tables so Postfix starts before the first heartbeat; it refuses
    # every recipient until the agent fills them in, which is the safe
    # default. They are built as orbitmail, which rewrites them from then on.
    local table
    for table in relay_domains relay_recipients; do
        [[ -f "$POSTFIX_DIR/$table" ]] || install -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0644 /dev/null "$POSTFIX_DIR/$table"
        runuser -u "$SERVICE_USER" -- postmap "${DB_TYPE}:${POSTFIX_DIR}/${table}"
    done

    # The pipe transport: Postfix runs the receive hook as orbitmail with the
    # message on stdin. The hook reads the node's settings from relay.env.
    if ! grep -q '^orbit ' /etc/postfix/master.cf; then
        cat >> /etc/postfix/master.cf <<'EOF'
orbit     unix  -       n       n       -       -       pipe
  flags=FRq user=orbitmail argv=/usr/local/bin/orbit-relay-receive ${recipient}
EOF
    fi
    postfix check
}

# --- Services -----------------------------------------------------------------

start() {
    runuser -u "$SERVICE_USER" -- /usr/local/bin/orbit-relay check >/dev/null \
        || die "The relay's configuration is unusable; see the errors above."
    log "Starting Postfix and the relay agent"
    systemctl enable --quiet postfix
    systemctl restart postfix
    systemctl enable --quiet "$SERVICE"
    systemctl restart "$SERVICE"
}

open_firewall() {
    if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q active; then
        log "Opening SMTP in ufw"
        ufw allow 25/tcp comment 'Orbit SMTP Relay' >/dev/null || true
    fi
}

verify() {
    [[ "$STATUS_PORT" != 0 ]] || return 0
    log "Waiting for the relay to report in"
    for _ in $(seq 1 20); do
        systemctl is-active --quiet "$SERVICE" || die "The ${SERVICE} service is not running. See: journalctl -u ${SERVICE}"
        if curl -fsS "http://127.0.0.1:${STATUS_PORT}/status" 2>/dev/null | grep -q '"server_reachable": true'; then
            log "Relay is up and talking to ${SERVER_URL}"
            return
        fi
        sleep 3
    done
    warn "The relay has not confirmed contact with the server yet. Check: journalctl -u ${SERVICE}"
}

check_os
resolve_settings
install_packages
fetch_source
migrate_from_docker
prepare_host
ensure_encryption_key
detect_db_type
write_env
install_files
configure_postfix
start
open_firewall
verify

cat <<SUMMARY

$(log "Relay node ${NODE_NAME} is installed.")

  Status        : orbit-relay status
                  curl -s http://127.0.0.1:${STATUS_PORT}/status | python3 -m json.tool
  Logs          : journalctl -u ${SERVICE} -f        (the agent)
                  journalctl -u 'postfix@*' -f       (Postfix)
  Services      : systemctl status ${SERVICE} postfix
  Configuration : ${ENV_FILE}
  Update        : re-run this install command (settings and keys are remembered)
  Encryption    : inbound mail is sealed to each reader's key before it reaches
                  the server. This node's own key is ${KEY_FILE}; back it up,
                  and show its id with: orbit-relay key show

Next: point each domain's MX record at ${RELAY_HOSTNAME}. For Orbit's own
fleet, also set it as the relay hostname on Mission Control's Mail page.
SUMMARY

if (( ${#MIGRATED_VOLUMES[@]} )); then
    cat <<DOCKER
The relay no longer uses Docker. Once mail flows, remove what is left of the
old container:

  docker volume rm ${MIGRATED_VOLUMES[*]}
  docker image rm orbit-relay:local
DOCKER
fi
