#!/usr/bin/env bash
# Container entrypoint for an Orbit SMTP Relay node.
#
# Postfix and the agent are both supervised by supervisord so that a crash in
# either is restarted without the whole node going down. This script only
# prepares the filesystem and writes Postfix's configuration from the
# environment; the agent keeps the domain and recipient tables current from the
# Orbit Mail server afterwards.

set -euo pipefail

# Operator commands (status, check, ping, logs, dead, key ...) need none of
# the Postfix setup below, and `key generate` must work before a key exists.
if [ "${1:-run}" != "run" ]; then
    exec /opt/orbit-relay/bin/orbit-relay "$@"
fi

MAILDROP_DIR="${ORBIT_MAILDROP_DIR:-/var/spool/orbit-mail/incoming}"
QUEUE_DIR="${ORBIT_QUEUE_DIR:-/var/lib/orbit-mail/queue}"
STATE_DIR="${ORBIT_STATE_DIR:-/var/lib/orbit-mail/state}"
POSTFIX_DIR="${ORBIT_POSTFIX_DIR:-/etc/postfix/orbit}"
DKIM_DIR="${ORBIT_DKIM_DIR:-/etc/orbit-mail/dkim}"
RELAY_HOSTNAME="${ORBIT_RELAY_HOSTNAME:-$(hostname -f 2>/dev/null || hostname)}"
MESSAGE_SIZE_LIMIT="${ORBIT_MESSAGE_SIZE_LIMIT:-52428800}"

log() { printf '%s [entrypoint] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"; }

mkdir -p "$MAILDROP_DIR" "$QUEUE_DIR" "$STATE_DIR" "$STATE_DIR/run" "$POSTFIX_DIR" "$DKIM_DIR"
chown -R orbitmail:orbitmail "$MAILDROP_DIR" "$QUEUE_DIR" "$STATE_DIR" "$POSTFIX_DIR" 2>/dev/null || true

echo "$RELAY_HOSTNAME" > /etc/mailname

# Empty tables so Postfix starts before the first heartbeat; it rejects every
# recipient until the agent fills them in, which is the safe default.
for table in relay_domains relay_recipients; do
    [ -f "$POSTFIX_DIR/$table" ] || : > "$POSTFIX_DIR/$table"
    postmap "hash:$POSTFIX_DIR/$table"
done

write_main_cf() {
    log "Writing main.cf for $RELAY_HOSTNAME"
    cat > /etc/postfix/main.cf <<EOF
# Generated by the Orbit Mail relay entrypoint. Edits here are overwritten on
# restart; change the environment variables instead.
compatibility_level = 3.6
myhostname = ${RELAY_HOSTNAME}
myorigin = \$myhostname
smtpd_banner = \$myhostname ESMTP Orbit Mail
inet_interfaces = all
inet_protocols = all
mydestination =
mynetworks = 127.0.0.0/8 [::1]/128
local_recipient_maps =
local_transport = error:local delivery is disabled

# --- Inbound: accept only the domains and addresses Orbit Mail told us about.
relay_domains = hash:${POSTFIX_DIR}/relay_domains
relay_recipient_maps = hash:${POSTFIX_DIR}/relay_recipients
smtpd_recipient_restrictions =
    permit_mynetworks,
    reject_unauth_destination,
    reject_unknown_recipient_domain,
    reject_unlisted_recipient,
    permit
smtpd_helo_required = yes
smtpd_sender_restrictions = reject_unknown_sender_domain
disable_vrfy_command = yes

# Everything accepted for a relay domain is handed to the agent, which queues
# it on disk and posts it to the Orbit Mail server.
relay_transport = orbit:
orbit_destination_recipient_limit = 1

# --- Outbound: mail submitted by the agent through sendmail goes straight out.
relayhost =
smtp_tls_security_level = may
smtp_tls_loglevel = 1
smtp_tls_CApath = /etc/ssl/certs

# --- Inbound TLS: opportunistic, with the host's certificate when mounted.
smtpd_tls_security_level = may
smtpd_tls_cert_file = ${ORBIT_TLS_CERT:-/etc/ssl/certs/ssl-cert-snakeoil.pem}
smtpd_tls_key_file = ${ORBIT_TLS_KEY:-/etc/ssl/private/ssl-cert-snakeoil.key}
smtpd_tls_loglevel = 1

message_size_limit = ${MESSAGE_SIZE_LIMIT}
maximal_queue_lifetime = 3d
bounce_queue_lifetime = 1d

# Postfix strips the environment before running the receive hook; these are
# the relay settings the hook needs (the encryption key path above all).
export_environment = TZ MAIL_CONFIG LANG ORBIT_RELAY_NAME ORBIT_RELAY_HOSTNAME ORBIT_QUEUE_DIR ORBIT_MAILDROP_DIR ORBIT_STATE_DIR ORBIT_LOG_BACKEND ORBIT_LOG_LEVEL ORBIT_MAX_RETRY_HOURS ORBIT_BACKOFF_BASE ORBIT_BACKOFF_MAX ORBIT_RELAY_ENCRYPTION_KEY ORBIT_RELAY_ENCRYPTION_KEY_FILE

# Logs go to stdout for docker logs.
maillog_file = /dev/stdout
EOF

    # The pipe transport: Postfix writes the message to the agent's maildrop
    # directory (named after the recipient) and runs `orbit-relay receive`.
    if ! grep -q '^orbit ' /etc/postfix/master.cf; then
        cat >> /etc/postfix/master.cf <<EOF
orbit     unix  -       n       n       -       -       pipe
  flags=FRq user=orbitmail argv=/usr/local/bin/orbit-relay-receive \${recipient}
EOF
    fi
}

write_main_cf

# OpenDKIM-free signing is left to a future release; when a DKIM key for the
# relay hostname is mounted we note it so the operator knows it is seen.
if ls "$DKIM_DIR"/*.private >/dev/null 2>&1; then
    log "DKIM private key(s) present in $DKIM_DIR"
fi

postfix set-permissions >/dev/null 2>&1 || true
postfix check || true

log "Node ${ORBIT_RELAY_NAME:-$(hostname -s)} -> ${ORBIT_MAIL_SERVER_URL:-unset}"
if [ -z "${ORBIT_RELAY_API_KEY:-}" ]; then
    log "WARNING: ORBIT_RELAY_API_KEY is unset. Mail will queue locally until a key is configured."
fi
# Every node seals mail before it reaches the server; there is no readable
# mode. The key comes from ORBIT_RELAY_ENCRYPTION_KEY (the key itself) or,
# normally, the file the installer mounts at /etc/orbit-mail/relay.key. The
# receive hook is started by Postfix as the orbitmail user, so the file
# mounted for root is copied where that user can read it, and the variable is
# re-pointed before supervisord (and so Postfix) inherits the environment.
if [ -z "${ORBIT_RELAY_ENCRYPTION_KEY:-}" ]; then
    KEY_FILE="${ORBIT_RELAY_ENCRYPTION_KEY_FILE:-/etc/orbit-mail/relay.key}"
    if [ ! -s "$KEY_FILE" ]; then
        log "ERROR: no encryption key at ${KEY_FILE}. The relay never stores mail readable, so it will not start without one."
        log "       Generate one on the host:  docker run --rm orbit-relay key generate | sudo tee /etc/orbit-mail/relay.key"
        log "       then mount it:             -v /etc/orbit-mail/relay.key:/etc/orbit-mail/relay.key:ro"
        log "       The installer (install.sh) does both."
        exit 1
    fi
    install -o orbitmail -g orbitmail -m 0400 "$KEY_FILE" "$STATE_DIR/relay.key"
    export ORBIT_RELAY_ENCRYPTION_KEY_FILE="$STATE_DIR/relay.key"
fi

if ! /opt/orbit-relay/bin/orbit-relay check; then
    log "ERROR: configuration is unusable; refusing to start."
    exit 1
fi

log "Starting supervisord"
exec /usr/bin/supervisord -n -c /app/deploy/supervisord.conf
