"""The durable outbound queue.

This is the component the whole relay exists to protect. When the web server
accepts a message, it is gone; when it does not, the message is on this disk
and will be retried until it lands. Nothing is held only in memory: a node
that loses power must not lose mail that Postfix already accepted from a
customer.

Layout on disk, one file per queued message::

    <queue_dir>/pending/<id>.json      ready to send
    <queue_dir>/inflight/<id>.json    being sent right now
    <queue_dir>/dead/<id>.json        given up on, kept for inspection

The split between ``pending`` and ``inflight`` is what makes delivery
crash-safe. A message is moved to ``inflight`` before the request is made, so a
process killed mid-send leaves it in a state that is retried on restart rather
than one that is silently lost. Anything in ``inflight`` when the agent starts
is moved back to ``pending`` by :meth:`Queue.recover_inflight`.

Each file is written to a temporary name and then renamed, because a rename
within a filesystem is atomic; a half-written JSON file would otherwise be
indistinguishable from a corrupt one.
"""

from __future__ import annotations

import json
import logging
import os
import random
import time
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


def _now():
    return datetime.now(timezone.utc)


def _utc(ts):
    return datetime.fromtimestamp(ts, tz=timezone.utc)


@dataclass
class QueuedMessage:
    """One message waiting to reach the web server."""

    #: Stable identifier, also the filename stem. Generated by the relay so the
    #: same message can be identified across restarts and across nodes.
    id: str = field(default_factory=lambda: uuid.uuid4().hex)
    recipient: str = ""
    envelope_from: str = ""
    #: The message as text, or, when ``encoding`` is ``base64``, the
    #: base64 ciphertext produced by the relay's encryption key.
    raw: str = ""
    encoding: str = ""
    received_at: str = ""
    relay_host: str = ""

    #: Set when the message was encrypted on this node: the non-secret
    #: parameters (key id, nonce, algorithm) the reader needs, the header
    #: block kept readable for routing and threading, and two hints the
    #: server can no longer compute for itself.
    encryption: dict = field(default_factory=dict)
    headers: str = ""
    has_attachments: bool = False
    plain_size: int = 0

    #: Scheduling state. `next_attempt_at` is an epoch float, kept numeric so
    #: comparison and sorting do not have to parse timestamps.
    attempts: int = 0
    next_attempt_at: float = 0.0
    first_seen_at: str = field(default_factory=lambda: _now().isoformat())
    last_attempt_at: str = ""
    last_error: str = ""
    #: Bytes of the raw message, for size reporting without re-reading it.
    size: int = 0

    @property
    def age_seconds(self):
        try:
            created = datetime.fromisoformat(self.first_seen_at)
        except (TypeError, ValueError):
            return 0
        if created.tzinfo is None:
            created = created.replace(tzinfo=timezone.utc)
        return (_now() - created).total_seconds()

    @property
    def is_encrypted(self):
        return bool(self.encryption)

    def to_dict(self):
        return asdict(self)

    @classmethod
    def from_dict(cls, data):
        known = {f for f in cls.__dataclass_fields__}
        return cls(**{k: v for k, v in data.items() if k in known})


def backoff_delay(attempt, base, maximum, jitter=0.25):
    """Seconds to wait before attempt number `attempt` (1-based).

    Exponential and capped, with jitter applied to the capped value. The order
    matters: jittering before the cap would let a single delay exceed
    ``maximum``, and jittering after it can push the delay 25% past the ceiling
    on a large fleet. Both are harmless in isolation, which is exactly why this
    is asserted in a test.

    The jitter is what stops every node in a fleet from retrying the same
    message on the same second once the web server comes back, which would
    look like a denial-of-service from the server's side at the moment it is
    least able to cope.
    """
    base_delay = min(maximum, base * (2 ** max(0, attempt - 1)))
    if jitter:
        spread = base_delay * jitter
        base_delay = min(maximum, base_delay + random.uniform(-spread, spread))
    return max(0.5, base_delay)


class Queue:
    """A filesystem-backed queue of messages awaiting delivery."""

    def __init__(self, root, max_attempts=0, max_age_hours=72, backoff_base=5.0,
                 backoff_max=300.0, backoff_jitter=0.25):
        self.root = os.path.abspath(root)
        self.pending_dir = os.path.join(self.root, "pending")
        self.inflight_dir = os.path.join(self.root, "inflight")
        self.dead_dir = os.path.join(self.root, "dead")

        self.max_attempts = max_attempts
        self.max_age_hours = max_age_hours
        self.backoff_base = backoff_base
        self.backoff_max = backoff_max
        self.backoff_jitter = backoff_jitter

    def ensure_dirs(self):
        for path in (self.pending_dir, self.inflight_dir, self.dead_dir):
            os.makedirs(path, exist_ok=True)

    # --- Writing ----------------------------------------------------------

    def enqueue(self, message, delay=0.0):
        """Persist a message for delivery.

        Called as early as possible in the pipeline, before any network call
        is attempted, so that a message is durable before anything can be lost.
        """
        self.ensure_dirs()
        # The dataclass already defaults a new message's id to a uuid hex
        # string, so an id that is empty here was set explicitly and is a bug
        # in the caller. Rejecting it is better than silently minting a new id,
        # which would overwrite nothing and lose the caller's identity.
        message.size = len(message.raw or "")
        message.first_seen_at = message.first_seen_at or _now().isoformat()
        message.next_attempt_at = time.time() + max(0.0, delay)
        self._write(self.pending_dir, message)
        return message

    def _path(self, directory, message_id):
        # `message_id` becomes a filename, so it is validated rather than
        # sanitised. Stripping bad characters would turn "../../etc/passwd"
        # into "etcpasswd", a silent, surprising rewrite. Rejecting it means a
        # caller that passes an untrusted id gets an error instead of a message
        # written somewhere unexpected.
        raw = str(message_id or "")
        if not raw or not raw.isascii() or not all(ch.isalnum() or ch in "-_" for ch in raw):
            raise ValueError(f"Invalid message id: {message_id!r}")
        return os.path.join(directory, f"{raw}.json")

    def _write(self, directory, message):
        path = self._path(directory, message.id)
        tmp = f"{path}.tmp"
        payload = json.dumps(message.to_dict(), ensure_ascii=False)
        with open(tmp, "w", encoding="utf-8") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp, path)
        # Fsync the directory so the rename itself survives a power loss, not
        # just the file contents.
        try:
            fd = os.open(directory, os.O_RDONLY)
            try:
                os.fsync(fd)
            finally:
                os.close(fd)
        except OSError:
            # Not supported on every filesystem; the file rename is still
            # atomic, so this is a durability nicety rather than correctness.
            pass

    # --- Reading ----------------------------------------------------------

    def recover_inflight(self):
        """Move anything in `inflight` back to `pending` at startup.

        A message is only in `inflight` while a request is in progress, so
        finding one means the process died mid-delivery. Retrying is correct:
        the web server deduplicates on message id.
        """
        self.ensure_dirs()
        recovered = []
        for name in sorted(os.listdir(self.inflight_dir)):
            if not name.endswith(".json"):
                continue
            source = os.path.join(self.inflight_dir, name)
            message = self._read(source)
            if message is None:
                # Unreadable rather than absent: park it so it is not retried
                # forever. It is kept, not deleted: a message that cannot be
                # parsed here may still be recoverable by hand, and silently
                # discarding customer mail is the worst possible outcome.
                self._quarantine(source)
                continue
            message.next_attempt_at = 0.0
            self._write(self.pending_dir, message)
            os.remove(source)
            recovered.append(message.id)
        return recovered

    def due(self, now=None, limit=50):
        """Messages ready to send, oldest first.

        Sorted by scheduled time rather than id so that a burst of arrivals is
        delivered in roughly the order it was received.
        """
        now = time.time() if now is None else now
        self.ensure_dirs()
        ready = []
        for name in os.listdir(self.pending_dir):
            if not name.endswith(".json"):
                continue
            message = self._read(os.path.join(self.pending_dir, name))
            if message is None:
                continue
            if message.next_attempt_at > now:
                continue
            if self._is_exhausted(message):
                self.move_to_dead(message, "retries exhausted")
                continue
            ready.append(message)

        ready.sort(key=lambda m: (m.next_attempt_at, m.first_seen_at))
        return ready[:limit]

    def _read(self, path):
        """Read one queue file, or None if it cannot be parsed.

        Defensive about the id inside the file as well as the filename: the
        contents are on disk and could have been written by an older version
        or edited by hand, so the id is validated before it is ever used to
        build another path.
        """
        try:
            with open(path, encoding="utf-8") as handle:
                data = json.load(handle)
        except (OSError, json.JSONDecodeError):
            return None
        if not isinstance(data, dict):
            return None
        try:
            message = QueuedMessage.from_dict(data)
            self._path(self.pending_dir, message.id)
        except (TypeError, ValueError):
            return None
        return message

    def _is_exhausted(self, message):
        """Whether a message has been tried for too long.

        Time is the primary limit, because a message that has been failing for
        three days is far more likely to be permanently undeliverable than one
        that has been failing for thirty seconds.
        """
        if self.max_attempts and message.attempts >= self.max_attempts:
            return True
        if self.max_age_hours and message.age_seconds > self.max_age_hours * 3600:
            return True
        return False

    # --- Delivery lifecycle ----------------------------------------------

    def mark_inflight(self, message):
        """Claim a message for an attempt.

        The claim is a filesystem move, so two processes sharing the queue
        cannot both take the same message; one of the two renames fails.
        """
        source = self._path(self.pending_dir, message.id)
        if not os.path.exists(source):
            return False
        self._write(self.inflight_dir, message)
        try:
            os.remove(source)
        except FileNotFoundError:
            return False
        return True

    def complete(self, message):
        """Delete a delivered message. Nothing to keep; the web server owns it."""
        self._remove(self._path(self.inflight_dir, message.id))

    def requeue(self, message, error="", when=None):
        """Return a failed message to the queue with backoff.

        The attempt counter is incremented here so it reflects every attempt
        actually made, including ones that failed before a request was sent.
        """
        message.attempts += 1
        message.last_attempt_at = _now().isoformat()
        message.last_error = (error or "")[:2000]
        delay = backoff_delay(
            message.attempts, self.backoff_base, self.backoff_max, self.backoff_jitter
        )
        message.next_attempt_at = time.time() + (delay if when is None else when)
        self._write(self.pending_dir, message)
        self._remove(self._path(self.inflight_dir, message.id))
        return message

    def move_to_dead(self, message, reason=""):
        """Park a message that will never succeed, keeping it for inspection."""
        message.last_error = (message.last_error or "") + f" | parked: {reason}".strip(" |")
        self._write(self.dead_dir, message)
        self._remove(self._path(self.pending_dir, message.id))
        self._remove(self._path(self.inflight_dir, message.id))
        return message

    def _quarantine(self, path):
        """Move an unreadable file into `dead/` so it stops being retried.

        `path` usually already lives in a queue directory (it comes from
        :meth:`recover_inflight`), so the basename is taken and rejoined rather
        than assuming the file is somewhere else. Returns True if it moved; a
        failure is logged rather than raised, because the caller's alternative
        is to keep retrying a file that can never be parsed. But it must not
        be silent, or a full disk would present as "the message is fine".
        """
        target = os.path.join(self.dead_dir, os.path.basename(path))
        if os.path.abspath(target) == os.path.abspath(path):
            return True
        try:
            os.replace(path, target)
            return True
        except OSError as error:
            logger.error("Could not quarantine %s: %s", path, error)
            return False

    def _remove(self, path):
        try:
            os.remove(path)
        except FileNotFoundError:
            pass

    # --- Reporting --------------------------------------------------------

    def stats(self):
        def count(directory):
            try:
                return len([n for n in os.listdir(directory) if n.endswith(".json")])
            except OSError:
                return 0

        return {
            "pending": count(self.pending_dir),
            "inflight": count(self.inflight_dir),
            "dead": count(self.dead_dir),
        }

    def peek(self, message_id):
        """Read one message from anywhere in the queue, for diagnostics."""
        for directory in (self.pending_dir, self.inflight_dir, self.dead_dir):
            message = self._read(self._path(directory, message_id))
            if message is not None:
                return message
        return None

    def list_dead(self, limit=20):
        try:
            names = [n for n in os.listdir(self.dead_dir) if n.endswith(".json")]
        except OSError:
            return []
        messages = []
        for name in sorted(names, reverse=True)[:limit]:
            message = self._read(os.path.join(self.dead_dir, name))
            if message is not None:
                messages.append(message)
        return messages

    def total_bytes(self):
        """Approximate on-disk size of queued mail, for the status endpoint."""
        total = 0
        for directory in (self.pending_dir, self.inflight_dir):
            try:
                names = os.listdir(directory)
            except OSError:
                continue
            for name in names:
                try:
                    total += os.path.getsize(os.path.join(directory, name))
                except OSError:
                    continue
        return total
